---
- name: Install required packages
  loop:
    - lvm2
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - lvm

- name: Create volume group
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.disks | join(',') }}"
  community.general.lvg:
    vg: "{{ item.group }}"
    pvs: "{{ item.disks | join(',') }}"
    pesize: "4"
  tags:
    - lvm

- name: Resize physical volume
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.disks | join(',') }}"
  changed_when: false
  ansible.builtin.command: "pvresize {{ item.disks | join(' ') }}"
  tags:
    - lvm

- name: Create logical volume
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  community.general.lvol:
    vg: "{{ item.group }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    resizefs: "{{ true if item.resizefs is undefined else item.resizefs }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - lvm

- name: Create volume filesystem
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  community.general.filesystem:
    fstype: "{{ 'ext4' if item.fstype is undefined else item.fstype }}"
    dev: "/dev/mapper/{{ item.group }}-{{ item.name | replace('-', '--') }}"
  tags:
    - lvm

- name: Mount volume filesystem
  loop: "{{ lvm_group_volumes + lvm_host_volumes }}"
  loop_control:
    label: "{{ item.group }}: {{ item.name }}"
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    src: "/dev/mapper/{{ item.group }}-{{ item.name | replace('-', '--') }}"
    fstype: "{{ 'ext4' if item.fstype is undefined else item.fstype }}"
    opts: "{{ ([] if item.mountopts is undefined else item.mountopts) | join(',') or omit }}"
    state: "{{ 'mounted' if item.state is undefined else ('mounted' if item.state == 'present' else 'absent') }}"
  tags:
    - lvm

...
